#!/bin/sh
# pull all repos and invalidate the cache on the ones that were updated.
# to be added as an hourly cron job.

cd "$(dirname "$0")/luapower" || exit 1

cc() { wget -qO- https://luapower.com/$pkg/cc; }
cc_all() { wget -qO- https://luapower.com/clear_cache; }
check() { grep -q -v 'Already up-to-date.'; }

mgit luapower-repos pull | check && REPOS_UPDATED=1

UNCLONED="$(mgit ls-uncloned)"
[ "$UNCLONED" ] && mgit clone-all
UNCLONED="$(mgit ls-uncloned)"
[ "$UNCLONED" ] && "There are still uncloned repos: $UNCLONED."

for pkg in $(mgit ls); do
	mgit - $pkg pull | check && cc $pkg && "Updated: $pkg."
done

cd "$(dirname "$0")" && git pull | check && "Updated: website."

[ "$REPOS_UPDATED" ] && cc_all
