#!/bin/sh
# pull all repos and invalidate the ones that were updated.
# to be added as an hourly cron job.

cd "$(dirname "$0")/luapower" || exit 1

for pkg in $(mgit ls); do

	mgit "$pkg" remote update

	LOCAL=$(git rev-parse @)
	BASE=$(git merge-base @ @{u})

	if [ $LOCAL = $BASE ]; then
		mgit "$pkg" pull
		wget -qO- https://luapower.com/$pkg/cc
	fi

done

