#!/bin/sh
# pull all repos and invalidate the cache on the ones that were updated.
# to be added as an hourly cron job.

cd "$(dirname "$0")/luapower" || exit 1

for pkg in $(mgit ls); do

	mgit "$pkg" pull | grep -q -v 'Already up-to-date.' && \
		wget -qO- https://luapower.com/$pkg/cc

done

